<?php
# This file was automatically generated by the Bricks installer. 
# If you make manual changes, please keep track in case you need to recreate them later.

$dbuser = getenv('C9_USER'); //MySQL database username
$dbpass = ''; //MySQL database password
$dbname = "c9";  //MySQL database name
$host = 'localhost';  //MySQL database host
$showhint = true;  //Shows the last executed SQL query
$server = getenv('IP');  //The protocol and server name to use in fully-qualified URLs
$scriptpath = '/release-channel';

// $servername = getenv('IP');
// $username = getenv('C9_USER');
// $password = "";
// $database = "c9";
$dbport = 3306;
?>